### ISSUE TITLE
Make "bucket-name" and "bucket-role-arn" flags mandatory globally

### ISSUE THREAD

**Issue by abstrask** [dfds/ce-cli#13]
We should expect to be able to access the S3 backend bucket for CLI for all commands.

Make "bucket-name" and "bucket-role-arn" flags mandatory globally. They're currently added to specific commands, like [PredefinedIamRoleCreateCmd](https://github.com/dfds/ce-cli/blob/a141d0a8f2bbf6a42d2bd6ce3ec31538b41a7477/cmd/aws/iam.go#L51).

They should be configurable via config files and/or environment variables anyway (#8).

**Comment by SEQUOIIA** [comment]
Reopen when needed.
