### ISSUE TITLE
Allow deploy of non-conflicting resources to accounts otherwise excluded through S3 file

### ISSUE THREAD

**Issue by abstrask** [dfds/ce-cli#14]
As per [#12](https://github.com/dfds/ce-cli/issues/12#issuecomment-1106659800):

> The functionality is now done, and just needs documenting. However, it has also become clear that it's a bit crude.
>
>The reason for doing this, is because an OIDC provider for the production cluster is managed by that pipeline in the Security, and shared Prod, account respectively. We don't want to interfere with resources managed by another tool.
>
>However, we may still want to deploy *other* OIDC providers in these accounts, not preventing the CLI tool from doing so.
>
>Not sure how to solve this right now. Maybe the scope somehow also need to include the resource name (or OIDC identifier in this case).

The exclusion defined in the S3 backend somehow need to also take resource identifiers into account, so we can deploy non-conflicting resources to the account, instead of preventing CLI from managing *any* resources of this type in the specified accounts.

**Comment by SEQUOIIA** [comment]
Reopen when needed.
